// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Author) GetID() int64 {
	return x.ID
}

func (x GetNextIDRow) GetPk() int64 {
	return x.Pk
}

func (x GetNextIDRow) GetPk_2() int64 {
	return x.Pk_2
}
