// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int32 {
	return x.ID
}

func (x InParams) GetID() int32 {
	return x.ID
}

func (x InParams) GetID_2() int32 {
	return x.ID_2
}
