// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() string {
	return x.ID
}

func (x Bar) GetInfo() []string {
	return x.Info
}

func (x Foo) GetID() string {
	return x.ID
}

func (x Foo) GetBar() string {
	return x.Bar
}
