package main

import (
	"fmt"
	"os"
	"runtime/debug"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/willabides/sqlcgetters"
)

var version string // set by linker

const description = `sqlcgetters generates getters for structs generated by sqlc.`

func main() {
	vars := kong.Vars{
		"version":     getVersion(),
		"VersionHelp": `Output the version and exit.`,
		"PathHelp":    `Path to sqlc output directory.`,
		"OutHelp":     `Output file. Default: stdout.`,
	}

	var cli cliRoot
	kctx := kong.Parse(&cli, vars, kong.Description(description))
	kctx.FatalIfErrorf(kctx.Run())
}

type cliRoot struct {
	Version kong.VersionFlag `kong:"help=${VersionHelp}"`
	Path    string           `kong:"arg,required,type=existingdir,help=${PathHelp}"`
}

func (c *cliRoot) Run(kctx *kong.Context) (err error) {
	fsys := os.DirFS(c.Path)
	sources, err := sqlcgetters.ListSQLCFiles(fsys, ".")
	if err != nil {
		return err
	}
	if len(sources) == 0 {
		return fmt.Errorf("no sqlc output found in %s", c.Path)
	}
	_, err = sqlcgetters.GenerateGetters(kctx.Stdout, fsys, sources...)
	return err
}

func getVersion() string {
	if version != "" {
		return "v" + strings.TrimPrefix(version, "v")
	}
	info, ok := debug.ReadBuildInfo()
	if ok {
		return info.Main.Version
	}
	return "(devel)"
}
