package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"

	"github.com/alecthomas/kong"
	"github.com/willabides/sqlcgetters"
)

var version string // set by linker

const description = `sqlcgetters generates getters for structs generated by sqlc.`

func main() {
	vars := kong.Vars{
		"version":     version,
		"VersionHelp": `Output the version and exit.`,
		"PathHelp":    `Path to sqlc output file. Can be glob. Default: "*.go".`,
		"OutHelp":     `Output file. Default: stdout.`,
	}
	if vars["version"] == "" {
		vars["version"] = "dev"
	}
	var cli cliRoot
	kctx := kong.Parse(&cli, vars, kong.Description(description))
	kctx.FatalIfErrorf(kctx.Run())
}

type cliRoot struct {
	Out     string           `kong:"short=o,help=${OutHelp}"`
	Version kong.VersionFlag `kong:"help=${VersionHelp}"`
	Path    []string         `kong:"arg,help=${PathHelp}"`
}

func (c *cliRoot) Run(kctx *kong.Context) (err error) {
	if len(c.Path) == 0 {
		c.Path = []string{"*.go"}
	}

	var buf bytes.Buffer
	_, err = sqlcgetters.GenerateGetters(&buf, os.DirFS("."), c.Path...)
	if err != nil {
		return err
	}

	// default to stdout
	if c.Out == "" {
		_, err = io.Copy(kctx.Stdout, &buf)
		return err
	}

	// write file with permissions from parent dir minus executable bit
	dirInfo, err := os.Stat(filepath.Dir(c.Out))
	if err != nil {
		return err
	}
	return os.WriteFile(c.Out, buf.Bytes(), dirInfo.Mode()&^0o111)
}
