// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Bar) GetName() string {
	return x.Name
}

func (x Bar) GetPhone() string {
	return x.Phone
}

func (x CountOneParams) GetID() int64 {
	return x.ID
}

func (x CountOneParams) GetName() string {
	return x.Name
}

func (x CountThreeParams) GetID() int64 {
	return x.ID
}

func (x CountThreeParams) GetPhone() string {
	return x.Phone
}

func (x CountThreeParams) GetName() string {
	return x.Name
}

func (x CountTwoParams) GetID() int64 {
	return x.ID
}

func (x CountTwoParams) GetName() string {
	return x.Name
}
