// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x FooPath) GetPointOne() sql.NullString {
	return x.PointOne
}

func (x FooPath) GetPointTwo() sql.NullString {
	return x.PointTwo
}
