// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x User) GetID() int32 {
	return x.ID
}

func (x User) GetFirstName() string {
	return x.FirstName
}

func (x User) GetLastName() sql.NullString {
	return x.LastName
}

func (x DeleteUsersByNameParams) GetFirstName() string {
	return x.FirstName
}

func (x DeleteUsersByNameParams) GetLastName() sql.NullString {
	return x.LastName
}

func (x GetUserByIDRow) GetFirstName() string {
	return x.FirstName
}

func (x GetUserByIDRow) GetID() int32 {
	return x.ID
}

func (x GetUserByIDRow) GetLastName() sql.NullString {
	return x.LastName
}

func (x InsertNewUserParams) GetFirstName() string {
	return x.FirstName
}

func (x InsertNewUserParams) GetLastName() sql.NullString {
	return x.LastName
}

func (x InsertNewUserWithResultParams) GetFirstName() string {
	return x.FirstName
}

func (x InsertNewUserWithResultParams) GetLastName() sql.NullString {
	return x.LastName
}

func (x ListUsersRow) GetFirstName() string {
	return x.FirstName
}

func (x ListUsersRow) GetLastName() sql.NullString {
	return x.LastName
}
