// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

func (x Author) GetID() int64 {
	return x.ID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Author) GetBio() sql.NullString {
	return x.Bio
}

func (x User) GetSub() uuid.UUID {
	return x.Sub
}
