// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Foo) GetNum() int32 {
	return x.Num
}

func (x MathRow) GetNum() int32 {
	return x.Num
}

func (x MathRow) GetDivision() int32 {
	return x.Division
}
