// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Foo) GetID() int64 {
	return x.ID
}

func (x Foo) GetBarID() sql.NullInt32 {
	return x.BarID
}

func (x RightJoinRow) GetID() sql.NullInt64 {
	return x.ID
}

func (x RightJoinRow) GetBarID() sql.NullInt32 {
	return x.BarID
}

func (x RightJoinRow) GetID_2() int64 {
	return x.ID_2
}
