// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Bar) GetC() sql.NullString {
	return x.C
}

func (x Bar) GetD() sql.NullString {
	return x.D
}

func (x Foo) GetA() sql.NullString {
	return x.A
}

func (x Foo) GetB() sql.NullString {
	return x.B
}

func (x StarExpansionJoinRow) GetA() sql.NullString {
	return x.A
}

func (x StarExpansionJoinRow) GetB() sql.NullString {
	return x.B
}

func (x StarExpansionJoinRow) GetC() sql.NullString {
	return x.C
}

func (x StarExpansionJoinRow) GetD() sql.NullString {
	return x.D
}
