// Code generated by sqlcgetters; DO NOT EDIT.

package override

import (
	"database/sql"

	fuid "github.com/gofrs/uuid"

	null "github.com/volatiletech/null/v8"

	null_v4 "gopkg.in/guregu/null.v4"

	orm "database/sql"

	uuid "github.com/gofrs/uuid"
)

func (x Bar) GetID() uuid.UUID {
	return x.ID
}

func (x Bar) GetOtherID() fuid.UUID {
	return x.OtherID
}

func (x Bar) GetMoreID() fuid.UUID {
	return x.MoreID
}

func (x Bar) GetAge() sql.NullInt32 {
	return x.Age
}

func (x Bar) GetBalance() interface{} {
	return x.Balance
}

func (x Bar) GetBio() sql.NullString {
	return x.Bio
}

func (x Bar) GetAbout() sql.NullString {
	return x.About
}

func (x Foo) GetID() uuid.UUID {
	return x.ID
}

func (x Foo) GetOtherID() fuid.UUID {
	return x.OtherID
}

func (x Foo) GetAge() orm.NullInt32 {
	return x.Age
}

func (x Foo) GetBalance() null.Float32 {
	return x.Balance
}

func (x Foo) GetBio() null_v4.String {
	return x.Bio
}

func (x Foo) GetAbout() *string {
	return x.About
}
