// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Foo) GetID() int64 {
	return x.ID
}

func (x GetBarRow) GetID() int64 {
	return x.ID
}

func (x GetBarRow) GetBarID() int64 {
	return x.BarID
}
