// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x FooBar) GetID() int64 {
	return x.ID
}

func (x FooBar) GetName() string {
	return x.Name
}

func (x SchemaScopedUpdateParams) GetName() string {
	return x.Name
}

func (x SchemaScopedUpdateParams) GetID() int64 {
	return x.ID
}
