// Code generated by sqlcgetters; DO NOT EDIT.

package override

import "github.com/kyleconroy/sqlc-testdata/pkg"

func (x Bar) GetOther() string {
	return x.Other
}

func (x Bar) GetTotal() int64 {
	return x.Total
}

func (x Bar) GetAlsoRetyped() pkg.CustomType {
	return x.AlsoRetyped
}

func (x Baz) GetOther() string {
	return x.Other
}

func (x Baz) GetTotal() int64 {
	return x.Total
}

func (x Baz) GetAlsoRetyped() pkg.CustomType {
	return x.AlsoRetyped
}

func (x Foo) GetOther() string {
	return x.Other
}

func (x Foo) GetTotal() int64 {
	return x.Total
}

func (x Foo) GetRetyped() pkg.CustomType {
	return x.Retyped
}
