package sqlcgetters

import (
	"bufio"
	"io/fs"
	"path"
	"strings"
)

const generatedBySQLC = `// Code generated by sqlc. DO NOT EDIT.`

// ListSQLCFiles returns all *.go files in a directory that were generated by sqlc by looking for sqlc's code
// generation comment.
func ListSQLCFiles(fsys fs.FS, dir string) ([]string, error) {
	var genFiles []string
	fileInfos, err := fs.ReadDir(fsys, dir)
	if err != nil {
		return nil, err
	}
	for _, info := range fileInfos {
		if !info.Type().IsRegular() {
			continue
		}
		if path.Ext(info.Name()) != ".go" {
			continue
		}
		var generated bool
		generated, err = isGeneratedBySQLC(fsys, dir, info.Name())
		if err != nil {
			return nil, err
		}
		if generated {
			genFiles = append(genFiles, path.Join(dir, info.Name()))
		}
	}
	return genFiles, nil
}

func isGeneratedBySQLC(fsys fs.FS, dir, filename string) (bool, error) {
	f, err := fsys.Open(path.Join(dir, filename))
	if err != nil {
		return false, err
	}
	var found bool
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), generatedBySQLC) {
			found = true
			break
		}
	}
	scannerErr := scanner.Err()
	err = f.Close()
	if err != nil {
		return false, err
	}
	if scannerErr != nil {
		return false, scannerErr
	}
	return found, nil
}
