// Code generated by sqlcgetters; DO NOT EDIT.

package hstore

import "github.com/jackc/pgtype"

func (x Foo) GetBar() pgtype.Hstore {
	return x.Bar
}

func (x Foo) GetBaz() pgtype.Hstore {
	return x.Baz
}
