// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import (
	"time"

	"github.com/google/uuid"
)

func (x TddTest) GetTestID() uuid.UUID {
	return x.TestID
}

func (x TddTest) GetTitle() string {
	return x.Title
}

func (x TddTest) GetDescr() string {
	return x.Descr
}

func (x TddTest) GetTsCreated() time.Time {
	return x.TsCreated
}

func (x TddTest) GetTsUpdated() time.Time {
	return x.TsUpdated
}
