// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Description) GetID() string {
	return x.ID
}

func (x Description) GetTxt() sql.NullString {
	return x.Txt
}
