// Code generated by sqlcgetters; DO NOT EDIT.

package db

func (x JoinTable) GetID() int64 {
	return x.ID
}

func (x JoinTable) GetPrimaryTableID() int64 {
	return x.PrimaryTableID
}

func (x JoinTable) GetOtherTableID() int64 {
	return x.OtherTableID
}

func (x JoinTable) GetIsActive() bool {
	return x.IsActive
}

func (x PrimaryTable) GetID() int64 {
	return x.ID
}

func (x PrimaryTable) GetUserID() int64 {
	return x.UserID
}

func (x UpdateJoinParams) GetIsActive() bool {
	return x.IsActive
}

func (x UpdateJoinParams) GetID() int64 {
	return x.ID
}

func (x UpdateJoinParams) GetUserID() int64 {
	return x.UserID
}

func (x UpdateLeftJoinParams) GetIsActive() bool {
	return x.IsActive
}

func (x UpdateLeftJoinParams) GetID() int64 {
	return x.ID
}

func (x UpdateLeftJoinParams) GetUserID() int64 {
	return x.UserID
}

func (x UpdateRightJoinParams) GetIsActive() bool {
	return x.IsActive
}

func (x UpdateRightJoinParams) GetID() int64 {
	return x.ID
}

func (x UpdateRightJoinParams) GetUserID() int64 {
	return x.UserID
}
