// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

func (x Foo) GetDescription() sql.NullString {
	return x.Description
}

func (x Foo) GetBar() uuid.NullUUID {
	return x.Bar
}

func (x Foo) GetBaz() uuid.UUID {
	return x.Baz
}
