// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetBar() sql.NullString {
	return x.Bar
}

func (x Foo) GetBat() string {
	return x.Bat
}

func (x Foo) GetBaz() sql.NullInt64 {
	return x.Baz
}

func (x Foo) GetQux() int64 {
	return x.Qux
}

func (x CoalesceNumericColumnsRow) GetBaz() sql.NullInt64 {
	return x.Baz
}

func (x CoalesceNumericColumnsRow) GetQux() int64 {
	return x.Qux
}

func (x CoalesceNumericColumnsRow) GetBaz_2() int64 {
	return x.Baz_2
}

func (x CoalesceNumericNullRow) GetBaz() sql.NullInt64 {
	return x.Baz
}

func (x CoalesceNumericNullRow) GetBaz_2() int64 {
	return x.Baz_2
}

func (x CoalesceStringColumnsRow) GetBar() sql.NullString {
	return x.Bar
}

func (x CoalesceStringColumnsRow) GetBat() string {
	return x.Bat
}

func (x CoalesceStringColumnsRow) GetBar_2() string {
	return x.Bar_2
}

func (x CoalesceStringNullRow) GetBar() sql.NullString {
	return x.Bar
}

func (x CoalesceStringNullRow) GetBar_2() string {
	return x.Bar_2
}
