// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x SuperUser) GetID() int32 {
	return x.ID
}

func (x SuperUser) GetFirstName() string {
	return x.FirstName
}

func (x SuperUser) GetLastName() sql.NullString {
	return x.LastName
}

func (x SuperUser) GetDateOfBirth() sql.NullTime {
	return x.DateOfBirth
}

func (x User) GetID() int32 {
	return x.ID
}

func (x User) GetLastName() sql.NullString {
	return x.LastName
}

func (x User) GetAge() int32 {
	return x.Age
}
