// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetBar() sql.NullString {
	return x.Bar
}

func (x Foo) GetBaz() sql.NullInt32 {
	return x.Baz
}

func (x SumBazRow) GetBar() sql.NullString {
	return x.Bar
}

func (x SumBazRow) GetQuantity() interface{} {
	return x.Quantity
}
