// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Bar) GetOwner() string {
	return x.Owner
}

func (x Foo) GetBarid() int64 {
	return x.Barid
}
