// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Bar) GetID() int32 {
	return x.ID
}

func (x Foo) GetID() int32 {
	return x.ID
}

func (x Foo) GetBar() sql.NullInt32 {
	return x.Bar
}

func (x TableNameParams) GetID() int32 {
	return x.ID
}

func (x TableNameParams) GetID_2() int32 {
	return x.ID_2
}
