// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetGroup() sql.NullString {
	return x.Group
}

func (x Foo) GetKey() sql.NullString {
	return x.Key
}
