// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x City) GetCityID() int32 {
	return x.CityID
}

func (x City) GetMayorID() int32 {
	return x.MayorID
}

func (x Mayor) GetMayorID() int32 {
	return x.MayorID
}

func (x Mayor) GetFullName() string {
	return x.FullName
}

func (x User) GetUserID() int32 {
	return x.UserID
}

func (x User) GetCityID() sql.NullInt32 {
	return x.CityID
}

func (x GetMayorsRow) GetUserID() int32 {
	return x.UserID
}

func (x GetMayorsRow) GetFullName() string {
	return x.FullName
}

func (x GetMayorsOptionalRow) GetUserID() int32 {
	return x.UserID
}

func (x GetMayorsOptionalRow) GetCityID() sql.NullInt32 {
	return x.CityID
}

func (x GetMayorsOptionalRow) GetFullName() sql.NullString {
	return x.FullName
}
