// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetA() sql.NullString {
	return x.A
}

func (x Foo) GetB() sql.NullInt32 {
	return x.B
}

func (x InsertValuesParams) GetA() sql.NullString {
	return x.A
}

func (x InsertValuesParams) GetB() sql.NullInt32 {
	return x.B
}
