// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "github.com/jackc/pgtype"

func (x Foo) GetBar() pgtype.Text {
	return x.Bar
}

func (x Foo) GetBam() pgtype.Name {
	return x.Bam
}

func (x Foo) GetBaz() pgtype.Name {
	return x.Baz
}
