// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x User) GetID() int32 {
	return x.ID
}

func (x User) GetFirstName() sql.NullString {
	return x.FirstName
}

func (x User) GetLastName() sql.NullString {
	return x.LastName
}

func (x SelectUserByIDParams) GetID() interface{} {
	return x.ID
}

func (x SelectUserByNameParams) GetName() sql.NullString {
	return x.Name
}

func (x SelectUserQuestionParams) GetColumn1() interface{} {
	return x.Column1
}

func (x SelectUserQuestionParams) GetColumn2() interface{} {
	return x.Column2
}
