// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Foo) GetName() string {
	return x.Name
}

func (x Foo) GetSlug() string {
	return x.Slug
}

func (x UpdateSetMultipleParams) GetName() string {
	return x.Name
}

func (x UpdateSetMultipleParams) GetSlug() string {
	return x.Slug
}
