// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

func (x Organisation) GetPartyID() uuid.UUID {
	return x.PartyID
}

func (x Organisation) GetName() string {
	return x.Name
}

func (x Organisation) GetLegalName() sql.NullString {
	return x.LegalName
}

func (x Party) GetPartyID() uuid.UUID {
	return x.PartyID
}

func (x Party) GetName() string {
	return x.Name
}

func (x Person) GetPartyID() uuid.UUID {
	return x.PartyID
}

func (x Person) GetName() string {
	return x.Name
}

func (x Person) GetFirstName() string {
	return x.FirstName
}

func (x Person) GetLastName() string {
	return x.LastName
}
