// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetA() sql.NullString {
	return x.A
}

func (x FooLimitOffsetParams) GetLimit() int32 {
	return x.Limit
}

func (x FooLimitOffsetParams) GetOffset() int32 {
	return x.Offset
}
