// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x BarNew) GetIDNew() int32 {
	return x.IDNew
}

func (x BarNew) GetIpOld() IPProtocol {
	return x.IpOld
}

func (x ListFooParams) GetIpOld() IPProtocol {
	return x.IpOld
}

func (x ListFooParams) GetIDNew() int32 {
	return x.IDNew
}

func (x ListFooRow) GetFooNew() int32 {
	return x.FooNew
}

func (x ListFooRow) GetBazOld() int32 {
	return x.BazOld
}
