// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "github.com/jackc/pgtype"

func (x Foo) GetA() pgtype.JSON {
	return x.A
}

func (x Foo) GetB() pgtype.JSONB {
	return x.B
}

func (x Foo) GetC() pgtype.JSON {
	return x.C
}

func (x Foo) GetD() pgtype.JSONB {
	return x.D
}
