// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Bar) GetA() sql.NullString {
	return x.A
}

func (x Bar) GetB() sql.NullString {
	return x.B
}

func (x Foo) GetA() sql.NullString {
	return x.A
}

func (x Foo) GetB() sql.NullString {
	return x.B
}

func (x FooByListParams) GetA() sql.NullString {
	return x.A
}

func (x FooByListParams) GetA_2() sql.NullString {
	return x.A_2
}

func (x FooByNotListParams) GetA() sql.NullString {
	return x.A
}

func (x FooByNotListParams) GetA_2() sql.NullString {
	return x.A_2
}
