// Code generated by sqlcgetters; DO NOT EDIT.

package override

import (
	"github.com/gofrs/uuid"
	fuid "github.com/gofrs/uuid"

	null "github.com/volatiletech/null/v8"

	null_v4 "gopkg.in/guregu/null.v4"

	orm "database/sql"
)

func (x Foo) GetID() uuid.UUID {
	return x.ID
}

func (x Foo) GetOtherID() fuid.UUID {
	return x.OtherID
}

func (x Foo) GetAge() orm.NullInt32 {
	return x.Age
}

func (x Foo) GetBalance() null.Float32 {
	return x.Balance
}

func (x Foo) GetBio() null_v4.String {
	return x.Bio
}

func (x Foo) GetAbout() *string {
	return x.About
}
