// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int32 {
	return x.ID
}

func (x Baz) GetID() int32 {
	return x.ID
}

func (x Foo) GetBarID() int32 {
	return x.BarID
}

func (x Foo) GetBazID() int32 {
	return x.BazID
}
