// Code generated by sqlcgetters; DO NOT EDIT.

package alpha

import (
	"time"
	tm "time"

	tm2 "time"
)

func (x Foo) GetBar() struct {
	Baz string `json:"baz"`
} {
	return x.Bar
}

func (x Foo) GetCreatedAt() tm.Time {
	return x.CreatedAt
}

func (x Foo) GetUpdatedAt() tm2.Time {
	return x.UpdatedAt
}

func (x Foo) GetDeletedAt() time.Time {
	return x.DeletedAt
}

func (x Foo) GetQux___() *string {
	return x.Qux
}

func (x Foo) GetGetQux___() string {
	return x.GetQux
}

func (x Foo) GetGetQux____() int32 {
	return x.GetQux_
}

func (x Foo) GetGetQux_____() int64 {
	return x.GetQux__
}

func (x Foo) GetGetGetQux() uint32 {
	return x.GetGetQux
}

func (x Foo) GetGetGetQux_() uint64 {
	return x.GetGetQux_
}

func (x Foo) GetGetGetQux__() interface{} {
	return x.GetGetQux__
}

func (x Foo) GetFunc() func(string) func(string) func(string) func(string) (*string, error) {
	return x.Func
}

func (x Bar) GetFoo() string {
	return x.Foo
}
