// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Baz) GetID() int64 {
	return x.ID
}

func (x Foo) GetBarID() int64 {
	return x.BarID
}

func (x Foo) GetBazID() int64 {
	return x.BazID
}
