// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x PlusPositionalCastParams) GetA() int32 {
	return x.A
}

func (x PlusPositionalCastParams) GetColumn2() int32 {
	return x.Column2
}
