// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "github.com/jackc/pgtype"

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray() pgtype.JSONB {
	return x.JsonbBuildArray
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_2() pgtype.JSONB {
	return x.JsonbBuildArray_2
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_3() pgtype.JSONB {
	return x.JsonbBuildArray_3
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_4() pgtype.JSONB {
	return x.JsonbBuildArray_4
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_5() pgtype.JSONB {
	return x.JsonbBuildArray_5
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject() pgtype.JSONB {
	return x.JsonbBuildObject
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_2() pgtype.JSONB {
	return x.JsonbBuildObject_2
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_3() pgtype.JSONB {
	return x.JsonbBuildObject_3
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_4() pgtype.JSONB {
	return x.JsonbBuildObject_4
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_5() pgtype.JSONB {
	return x.JsonbBuildObject_5
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray() pgtype.JSON {
	return x.JsonBuildArray
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_2() pgtype.JSON {
	return x.JsonBuildArray_2
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_3() pgtype.JSON {
	return x.JsonBuildArray_3
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_4() pgtype.JSON {
	return x.JsonBuildArray_4
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_5() pgtype.JSON {
	return x.JsonBuildArray_5
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject() pgtype.JSON {
	return x.JsonBuildObject
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_2() pgtype.JSON {
	return x.JsonBuildObject_2
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_3() pgtype.JSON {
	return x.JsonBuildObject_3
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_4() pgtype.JSON {
	return x.JsonBuildObject_4
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_5() pgtype.JSON {
	return x.JsonBuildObject_5
}
