// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetA() sql.NullString {
	return x.A
}

func (x Foo) GetB() sql.NullString {
	return x.B
}

func (x StarExpansionRow) GetA() sql.NullString {
	return x.A
}

func (x StarExpansionRow) GetB() sql.NullString {
	return x.B
}

func (x StarExpansionRow) GetA_2() sql.NullString {
	return x.A_2
}

func (x StarExpansionRow) GetB_2() sql.NullString {
	return x.B_2
}

func (x StarExpansionRow) GetA_3() sql.NullString {
	return x.A_3
}

func (x StarExpansionRow) GetB_3() sql.NullString {
	return x.B_3
}
