// Code generated by sqlcgetters; DO NOT EDIT.

package override

import (
	"github.com/kyleconroy/sqlc-testdata/pkg"
	"github.com/lib/pq"
)

func (x Foo) GetOther() string {
	return x.Other
}

func (x Foo) GetTotal() int64 {
	return x.Total
}

func (x Foo) GetTags() []string {
	return x.Tags
}

func (x Foo) GetByteSeq() []byte {
	return x.ByteSeq
}

func (x Foo) GetRetyped() pkg.CustomType {
	return x.Retyped
}

func (x Foo) GetLangs() pq.StringArray {
	return x.Langs
}
