// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Foo) GetA() int32 {
	return x.A
}

func (x Foo) GetB() int32 {
	return x.B
}

func (x Foo) GetC() sql.NullInt32 {
	return x.C
}
