// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x User) GetFirstName() sql.NullString {
	return x.FirstName
}

func (x User) GetLastName() sql.NullString {
	return x.LastName
}

func (x User) GetAge() int16 {
	return x.Age
}
