// Code generated by sqlcgetters; DO NOT EDIT.

package db

import "database/sql"

func (x Author) GetID() int64 {
	return x.ID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Author) GetBio() sql.NullString {
	return x.Bio
}

func (x UpsertAuthorParams) GetName() string {
	return x.Name
}

func (x UpsertAuthorParams) GetBio() sql.NullString {
	return x.Bio
}

func (x UpsertAuthorNamedParams) GetName() string {
	return x.Name
}

func (x UpsertAuthorNamedParams) GetBio() sql.NullString {
	return x.Bio
}
