// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x User) GetID() int64 {
	return x.ID
}

func (x User) GetFirstName() string {
	return x.FirstName
}

func (x User) GetLastName() sql.NullString {
	return x.LastName
}

func (x User) GetAge() int64 {
	return x.Age
}
