// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetName() string {
	return x.Name
}

func (x Bar) GetReady() bool {
	return x.Ready
}

func (x Foo) GetName() string {
	return x.Name
}

func (x Foo) GetMeta() string {
	return x.Meta
}

func (x InsertSelectParams) GetMeta() string {
	return x.Meta
}

func (x InsertSelectParams) GetReady() bool {
	return x.Ready
}
