// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Bar) GetID() int32 {
	return x.ID
}

func (x Bar) GetParentID() sql.NullInt32 {
	return x.ParentID
}

func (x CTERecursiveRow) GetID() int32 {
	return x.ID
}

func (x CTERecursiveRow) GetParentID() sql.NullInt32 {
	return x.ParentID
}
