#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/gofumpt bin/handcrafted >/dev/null

filter="{{ range .GoFiles }}{{$.Dir}}/{{.}}
{{ end }}{{ range .TestGoFiles }}{{$.Dir}}/{{.}}
{{ end }}{{ range .XTestGoFiles }}{{$.Dir}}/{{.}}
{{ end }}"

go list -f "$filter" ./... | bin/handcrafted | xargs bin/gofumpt -w
