// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Foo) GetName() string {
	return x.Name
}

func (x Foo) GetSlug() string {
	return x.Slug
}

func (x UpdateSetParams) GetName() string {
	return x.Name
}

func (x UpdateSetParams) GetSlug() string {
	return x.Slug
}
