// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Event) GetID() sql.NullInt32 {
	return x.ID
}

func (x HandledEvent) GetLastHandledID() sql.NullInt32 {
	return x.LastHandledID
}

func (x HandledEvent) GetHandler() sql.NullString {
	return x.Handler
}
