// Code generated by sqlcgetters; DO NOT EDIT.

package db

import "database/sql"

func (x X) GetA() sql.NullString {
	return x.A
}

func (x X) GetB() sql.NullString {
	return x.B
}

func (x Y) GetA() sql.NullString {
	return x.A
}

func (x Y) GetB() sql.NullString {
	return x.B
}
