// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetReady() bool {
	return x.Ready
}

func (x CTECountRow) GetCount() int64 {
	return x.Count
}

func (x CTECountRow) GetCount_2() int64 {
	return x.Count_2
}
