// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Bar) GetID() int64 {
	return x.ID
}

func (x Foo) GetID() int64 {
	return x.ID
}

func (x Foo) GetBar() int64 {
	return x.Bar
}

func (x TableNameParams) GetID() int64 {
	return x.ID
}

func (x TableNameParams) GetID_2() int64 {
	return x.ID_2
}
