// Code generated by sqlcgetters; DO NOT EDIT.

package jets

func (x Jet) GetID() int32 {
	return x.ID
}

func (x Jet) GetPilotID() int32 {
	return x.PilotID
}

func (x Jet) GetAge() int32 {
	return x.Age
}

func (x Jet) GetName() string {
	return x.Name
}

func (x Jet) GetColor() string {
	return x.Color
}

func (x Language) GetID() int32 {
	return x.ID
}

func (x Language) GetLanguage() string {
	return x.Language
}

func (x Pilot) GetID() int32 {
	return x.ID
}

func (x Pilot) GetName() string {
	return x.Name
}

func (x PilotLanguage) GetPilotID() int32 {
	return x.PilotID
}

func (x PilotLanguage) GetLanguageID() int32 {
	return x.LanguageID
}
