// Code generated by sqlcgetters; DO NOT EDIT.

package aggregate_functions

import "database/sql"

func (x GroupConcatRow) GetStudentName() sql.NullString {
	return x.StudentName
}

func (x GroupConcatRow) GetGroupConcat() sql.NullString {
	return x.GroupConcat
}

func (x GroupConcatOrderByRow) GetStudentName() sql.NullString {
	return x.StudentName
}

func (x GroupConcatOrderByRow) GetGroupConcat() sql.NullString {
	return x.GroupConcat
}

func (x Student) GetStudentName() sql.NullString {
	return x.StudentName
}

func (x Student) GetScore() sql.NullFloat64 {
	return x.Score
}
