// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "encoding/json"

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray() json.RawMessage {
	return x.JsonbBuildArray
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_2() json.RawMessage {
	return x.JsonbBuildArray_2
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_3() json.RawMessage {
	return x.JsonbBuildArray_3
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_4() json.RawMessage {
	return x.JsonbBuildArray_4
}

func (x SelectJSONBBuildArrayRow) GetJsonbBuildArray_5() json.RawMessage {
	return x.JsonbBuildArray_5
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject() json.RawMessage {
	return x.JsonbBuildObject
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_2() json.RawMessage {
	return x.JsonbBuildObject_2
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_3() json.RawMessage {
	return x.JsonbBuildObject_3
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_4() json.RawMessage {
	return x.JsonbBuildObject_4
}

func (x SelectJSONBBuildObjectRow) GetJsonbBuildObject_5() json.RawMessage {
	return x.JsonbBuildObject_5
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray() json.RawMessage {
	return x.JsonBuildArray
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_2() json.RawMessage {
	return x.JsonBuildArray_2
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_3() json.RawMessage {
	return x.JsonBuildArray_3
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_4() json.RawMessage {
	return x.JsonBuildArray_4
}

func (x SelectJSONBuildArrayRow) GetJsonBuildArray_5() json.RawMessage {
	return x.JsonBuildArray_5
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject() json.RawMessage {
	return x.JsonBuildObject
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_2() json.RawMessage {
	return x.JsonBuildObject_2
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_3() json.RawMessage {
	return x.JsonBuildObject_3
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_4() json.RawMessage {
	return x.JsonBuildObject_4
}

func (x SelectJSONBuildObjectRow) GetJsonBuildObject_5() json.RawMessage {
	return x.JsonBuildObject_5
}
