// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import (
	"encoding/json"

	"github.com/tabbed/pqtype"
)

func (x Foo) GetA() json.RawMessage {
	return x.A
}

func (x Foo) GetB() json.RawMessage {
	return x.B
}

func (x Foo) GetC() pqtype.NullRawMessage {
	return x.C
}

func (x Foo) GetD() pqtype.NullRawMessage {
	return x.D
}
