// Code generated by sqlcgetters; DO NOT EDIT.

package db

import "database/sql"

func (x Bar) GetColA() sql.NullBool {
	return x.ColA
}

func (x Bar) GetColB() sql.NullBool {
	return x.ColB
}

func (x Bar) GetColC() sql.NullBool {
	return x.ColC
}

func (x Foo) GetColA() bool {
	return x.ColA
}

func (x Foo) GetColB() bool {
	return x.ColB
}

func (x Foo) GetColC() bool {
	return x.ColC
}
