// Code generated by sqlcgetters; DO NOT EDIT.

package db

import "database/sql"

func (x Author) GetID() int64 {
	return x.ID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Author) GetBio() sql.NullString {
	return x.Bio
}

func (x CreateAuthorParams) GetName() string {
	return x.Name
}

func (x CreateAuthorParams) GetBio() sql.NullString {
	return x.Bio
}
