// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Author) GetID() int64 {
	return x.ID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Author) GetBio() sql.NullString {
	return x.Bio
}

func (x Book) GetID() int64 {
	return x.ID
}

func (x Book) GetAuthorID() int64 {
	return x.AuthorID
}

func (x Book) GetTitle() string {
	return x.Title
}

func (x GetAuthorsWithBooksCountRow) GetID() int64 {
	return x.ID
}

func (x GetAuthorsWithBooksCountRow) GetName() string {
	return x.Name
}

func (x GetAuthorsWithBooksCountRow) GetBio() sql.NullString {
	return x.Bio
}

func (x GetAuthorsWithBooksCountRow) GetBooksCount() int64 {
	return x.BooksCount
}
