// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Product) GetID() int64 {
	return x.ID
}

func (x Product) GetName() string {
	return x.Name
}

func (x Product) GetPrice() int32 {
	return x.Price
}

func (x GetBetweenPricesParams) GetPrice() int32 {
	return x.Price
}

func (x GetBetweenPricesParams) GetPrice_2() int32 {
	return x.Price_2
}

func (x GetBetweenPricesTableParams) GetPrice() int32 {
	return x.Price
}

func (x GetBetweenPricesTableParams) GetPrice_2() int32 {
	return x.Price_2
}

func (x GetBetweenPricesTableAliasParams) GetPrice() int32 {
	return x.Price
}

func (x GetBetweenPricesTableAliasParams) GetPrice_2() int32 {
	return x.Price_2
}
