// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "time"

func (x GenerateSeriesParams) GetColumn1() time.Time {
	return x.Column1
}

func (x GenerateSeriesParams) GetColumn2() time.Time {
	return x.Column2
}
