// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "github.com/google/uuid"

func (x Foo) GetID() uuid.UUID {
	return x.ID
}

func (x Foo) GetOtherID() uuid.UUID {
	return x.OtherID
}

func (x Foo1) GetID() uuid.UUID {
	return x.ID
}

func (x Foo1) GetOtherID() uuid.UUID {
	return x.OtherID
}
