// Code generated by sqlcgetters; DO NOT EDIT.

package booktest

import (
	"database/sql"
	"time"
)

func (x Author) GetAuthorID() int32 {
	return x.AuthorID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Book) GetBookID() int32 {
	return x.BookID
}

func (x Book) GetAuthorID() int32 {
	return x.AuthorID
}

func (x Book) GetIsbn() string {
	return x.Isbn
}

func (x Book) GetBookType() BookType {
	return x.BookType
}

func (x Book) GetTitle() string {
	return x.Title
}

func (x Book) GetYear() int32 {
	return x.Year
}

func (x Book) GetAvailable() time.Time {
	return x.Available
}

func (x Book) GetTags() []string {
	return x.Tags
}

func (x BooksByTagsRow) GetBookID() int32 {
	return x.BookID
}

func (x BooksByTagsRow) GetTitle() string {
	return x.Title
}

func (x BooksByTagsRow) GetName() sql.NullString {
	return x.Name
}

func (x BooksByTagsRow) GetIsbn() string {
	return x.Isbn
}

func (x BooksByTagsRow) GetTags() []string {
	return x.Tags
}

func (x BooksByTitleYearParams) GetTitle() string {
	return x.Title
}

func (x BooksByTitleYearParams) GetYear() int32 {
	return x.Year
}

func (x CreateBookParams) GetAuthorID() int32 {
	return x.AuthorID
}

func (x CreateBookParams) GetIsbn() string {
	return x.Isbn
}

func (x CreateBookParams) GetBookType() BookType {
	return x.BookType
}

func (x CreateBookParams) GetTitle() string {
	return x.Title
}

func (x CreateBookParams) GetYear() int32 {
	return x.Year
}

func (x CreateBookParams) GetAvailable() time.Time {
	return x.Available
}

func (x CreateBookParams) GetTags() []string {
	return x.Tags
}

func (x UpdateBookParams) GetTitle() string {
	return x.Title
}

func (x UpdateBookParams) GetTags() []string {
	return x.Tags
}

func (x UpdateBookParams) GetBookID() int32 {
	return x.BookID
}

func (x UpdateBookISBNParams) GetTitle() string {
	return x.Title
}

func (x UpdateBookISBNParams) GetTags() []string {
	return x.Tags
}

func (x UpdateBookISBNParams) GetBookID() int32 {
	return x.BookID
}

func (x UpdateBookISBNParams) GetIsbn() string {
	return x.Isbn
}
