// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Arena) GetName() sql.NullString {
	return x.Name
}

func (x Location) GetName() sql.NullString {
	return x.Name
}
