// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Campus) GetID() string {
	return x.ID
}

func (x ProductMetum) GetID() string {
	return x.ID
}

func (x Student) GetID() string {
	return x.ID
}
