// Code generated by sqlcgetters; DO NOT EDIT.

package db

func (x JoinTable) GetID() int32 {
	return x.ID
}

func (x JoinTable) GetPrimaryTableID() int32 {
	return x.PrimaryTableID
}

func (x JoinTable) GetOtherTableID() int32 {
	return x.OtherTableID
}

func (x JoinTable) GetIsActive() bool {
	return x.IsActive
}

func (x PrimaryTable) GetID() int32 {
	return x.ID
}

func (x PrimaryTable) GetUserID() int32 {
	return x.UserID
}

func (x UpdateJoinParams) GetIsActive() bool {
	return x.IsActive
}

func (x UpdateJoinParams) GetID() int32 {
	return x.ID
}

func (x UpdateJoinParams) GetUserID() int32 {
	return x.UserID
}
