// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

func (x Foo) GetBar() string {
	return x.Bar
}

func (x Foo) GetBat() string {
	return x.Bat
}

func (x LowerSwitchedOrderParams) GetBar() string {
	return x.Bar
}

func (x LowerSwitchedOrderParams) GetLower() string {
	return x.Lower
}
