// Code generated by sqlcgetters; DO NOT EDIT.

package querytest

import "database/sql"

func (x Author) GetID() int32 {
	return x.ID
}

func (x Author) GetName() string {
	return x.Name
}

func (x Author) GetParentID() sql.NullInt32 {
	return x.ParentID
}

func (x AllAuthorsRow) GetID() int32 {
	return x.ID
}

func (x AllAuthorsRow) GetName() string {
	return x.Name
}

func (x AllAuthorsRow) GetAliasID() sql.NullInt32 {
	return x.AliasID
}

func (x AllAuthorsRow) GetAliasName() sql.NullString {
	return x.AliasName
}
